- README.md
Hopefully better than nothing, but you'll probably want to do better examples at some point :-)
> README install and usage examples

- README.md
- index.js
Array.isArray is faster than checking using Object.prototype.toString and is supported in modern browsers. React requires es5-shim.js (which includes Array.isArray) to support IE8. I modified the tests from #16 for benchmarks; pretty decent improvements shown.
http://jsperf.com/classnames-util/5
> Use Array.isArray to check for array

- .travis.yml
- README.md
@dcousens @JedWatson separate out travis CI sauce
> add travis configs

- dedupe.js
- tests.js
> allow object to remove previous class, also dedupes class names

- dedupe.js
- index.js
Fixes #37 
Just in case removing `use strict` affects performance. I ran the benchmark and didn't noticed much of a difference. Not sure if I need to add tests to this either. And let me know if you guys want a jsperf.
Cheers!
> Add umd wrapper

- dedupe.js
- index.js
This is to fix issue talked about here: https://github.com/JedWatson/classnames/issues/40
> fixes issue where AMD and CommonJS are both used on the same page.

- index.js
Easier than fixing merge conflicts with #47
> Name the AMD module

- dedupe.js
See https://github.com/JedWatson/classnames/pull/50#issuecomment-144226892
> Remove Object.keys implementation (for now).

- README.md
import from 'classnames/bind' and assigned the binded function to a new variable (babel reporting classNames is readonly)
> Update README.md to properly reflect working API

- index.js
Hey this will avoid an issue when using Dojo loader: TypeError: deps.map is not a function
http://stackoverflow.com/a/29312237/5605390
> Add deps parameter to the AMD module

- README.md
Hey I found the lack of a falsey example pretty confusing, let me know if you have a better one.
> Added falsey example

- .npmignore
tests, benchmarks and config files made up into a package. Fixed.
> Better .npmignore

- .travis.yml
Swap out io.js testing for stable node
> travis: drop iojs, add stable node

- .gitignore
- benchmarks/benchmarks.html
- benchmarks/fixtures.js
- benchmarks/run.js
- benchmarks/runChecks.js
- benchmarks/runInBrowser.js
- benchmarks/runSuite.js
- package.json
- Added HTML page
- Refactored benchmarking code to allow its reuse
> Added benchmarks for browsers

- README.md
Just a bit of small improvements for readme page.
> Slightly tweaked a README.md

- README.md
- index.d.ts
@adidahiya @JKillian @seansfkelley @mradamczyk @marvinhagemeister @ccapndave this should be enough?
As follow up to https://github.com/JedWatson/classnames/pull/103 (ref https://github.com/JedWatson/classnames/pull/103#issuecomment-426866682)
IANAL,  but,  I think this is ok.
Pinged the authors anyway...
> add typescript contributor copyright notice

- bind.d.ts
- dedupe.d.ts
- index.d.ts
Main purpose is to define both, named and default export which package does;
`.d.ts` files size reduced making direct exports where it is possible;
> Types definition improvements

- .github/workflows/node.js.yml
- .travis.yml
- README.md
This PR replaces the existing CI integrations, with GitHub workflows
> add nodejs test workflow

- .github/workflows/node.js.yml
Fixes a configuration error so that GitHub Actions will run correctly.
> Fix misconfigured 'fail-fast' option

- .github/workflows/node.js.yml
- bind.d.ts
- classnames-test.ts
- dedupe.d.ts
- index.d.ts
- package-lock.json
- package.json
- tsconfig.json
- tslint.json
This asserts the types work in TypeScript 3.0 and above. Some issues were uncovered by the tests. These have been fixed.
Closes #249
> Add TypeScript tests using dtslint

- package-lock.json
- tests/types.ts
Nothing too interesting, only adding additional verbosity in testing N>1 parameter calls
> Add additional types tests

- README.md
> Update README with new shields.io badges

- .editorconfig
- .github/dependabot.yml
- .github/workflows/node.js.yml
- .github/workflows/release.yml
Refactors the workflows to deal with some low-hanging fruit, specifically making the various workflows more consistent. See comments below for a list of detailed changes.
> Refactor workflows with various enhancements

- .github/dependabot.yml
- package-lock.json
Adds a Dependabot configuration to keep the NPM dependencies up-to-date.
> Add Dependabot configuration for NPM dependencies

- package-lock.json
Updates `classnames` to the latest version for the benchmarks.
> Bump `classnames` to the latest version

- dedupe.js
> Use string concatenation to speed up dedupe

- bind.js
- dedupe.js
- index.js
<details>
<summary>Benchmarks</summary>
```
classnames git:(refactor) npm run bench   
> classnames@2.5.1 bench
> node ./benchmarks/run.js
(node:95772) ExperimentalWarning: Importing JSON modules is an experimental feature and might change at any time
(Use `node --trace-warnings ...` to show where the warning was created)
Benchmarking 'strings'.
| Task Name     | ops/sec    | Average Time (ns)  | Margin | Samples |
| ------------- | ---------- | ------------------ | ------ | ------- |
| default/local | 12,902,063 | 77.50698016049525  | ±0.94% | 6451032 |
| default/npm   | 15,087,679 | 66.27924267843498  | ±0.54% | 7543841 |
| bind/local    | 12,459,259 | 80.26158996638294  | ±0.81% | 6229630 |
| bind/npm      | 13,227,651 | 75.59920808713574  | ±2.60% | 6613827 |
| dedupe/local  | …
```
> refactor: directly return newClass on falsy value

- index.d.ts
- tests/index.mjs
- tests/index.test-d.ts
target v2 branch; https://github.com/JedWatson/classnames/pull/392
> fix: new @types/react support
