index.js
tests.js

Fixes #3 (didn't feel like submitting individual PRs)
- Return empty string rather than `undefined`. Better behaviour imo and good for type checking in the future.
- camelCase `classNames`. This doesn't affect anything since the user can rename it anyways during `require`. Just thought it'd be more consistent.
- Make the function not crash on `null`.

Return empty string; Fix null crash; Add tests; camelCase

---

index.js
tests.js

The function ignores non-string values. This has always been the case. No behavior change here.
Addtionally, the function's now consistently 4x faster due to less allocations. I kept the allocation for `classNames`, because it turns out that it's faster to mutate an array and join it at the end than to continuously append to a string, especially for slightly longer class names.
Fixes #5

Make code uglier and faster; more precise test

---

README.md
index.js
tests.js

A bit trivial but this was in discordance with the README, which stated
that "falsy keys won't be included". Previously `1` was ignored.
Same for empty string. `c('a', '')` gave `"a "`. Fixed that.
P.S. I hate JS implicit conversion and falsy values

Fix behavior for non-zero params & empty string

---

package.json

npm automatically includes `~/node_modules/.bin` in the PATH when running scripts; so there is no need to specify this.
It will not revert to the globally installed `mocha` unless the package is missing.

package: remove unnecessary pathing

---

index.js

This prevents needing to use `continue` and explicitly defines the case
where the class should be added.

Simplify loop to only the asserted case

---

index.js
tests.js

Here's another implementation to support Arrays. This also removes the use of Array#join in favor of String concatenation. [JSPerf] (http://jsperf.com/classnames-util/3)

Adds support for Arrays and Performance Improvements

---

index.js

For issue https://github.com/JedWatson/classnames/issues/29

UMD Wrapper

---

index.js

Want the license header to be preserved when this library is
included in a project.

Add contents of LICENSE to top of index.js

---

index.js

```typeof``` not as harmless as it may seem, so reduce it to one call

Get argument typeof only once, for performance

---

README.md

It's not immediately obvious that a string can be used as a key in the readme object notation example .  Further, trying to use a hyphen in a key that _isn't_ a string can cause all sorts of unwelcome stuff.  So I thought it'd be beneficial to add this.

Update readme to include string key in object notation

---

index.js

A rebase of #36.
Using node `v4.1.1`:
``` javascript
* local#strings x 6,045,951 ops/sec ±1.58% (97 runs sampled)
*   npm#strings x 3,216,399 ops/sec ±4.18% (88 runs sampled)
> Fastest is local#strings
* local#object x 2,542,831 ops/sec ±1.06% (98 runs sampled)
*   npm#object x 2,526,207 ops/sec ±1.12% (91 runs sampled)
> Fastest is local#object |   npm#object
* local#mix x 948,129 ops/sec ±1.53% (93 runs sampled)
*   npm#mix x 1,265,072 ops/sec ±0.97% (96 runs sampled)
> Fastest is npm#mix
* local#arrays x 623,087 ops/sec ±0.69% (98 runs sampled)
*   npm#arrays x 814,812 ops/sec ±0.69% (103 runs sampled)
> Fastest is npm#arrays
```
Performance TL;DR:
* pure string case is 180% faster
* objects are the same
* (string, object), arrays and multiple objects (mix) are all 25% slower
Its a …

use [].join over concatenation

---

README.md
dedupe.js

Here are benchmark results:
```
> classnames@2.2.3 benchmarks /home/ja/code/classnames
> node ./benchmarks/run
* local#strings x 5,636,517 ops/sec ±0.44% (101 runs sampled)
*   npm#strings x 5,630,325 ops/sec ±0.57% (99 runs sampled)
* local/dedupe#strings x 902,229 ops/sec ±1.89% (91 runs sampled)
*   npm/dedupe#strings x 463,660 ops/sec ±0.47% (98 runs sampled)
> Fastest is local#strings |   npm#strings
* local#object x 2,655,968 ops/sec ±0.54% (98 runs sampled)
*   npm#object x 2,676,877 ops/sec ±0.17% (101 runs sampled)
* local/dedupe#object x 1,721,874 ops/sec ±0.64% (96 runs sampled)
*   npm/dedupe#object x 826,229 ops/sec ±0.52% (94 runs sampled)
> Fastest is npm#object | local#object
* local#strings, object x 2,895,452 ops/sec ±0.51% (99 runs sampled)
*   npm#strings, object x …
```

Improve dedupe version performance

---

dedupe.js

Creating instances with `new` of an object that inherits from `Object.create(null)` is faster than creating an object with `Object.create(null)` over-and-over.
```
$ npm run benchmarks
> classnames@2.2.4 benchmarks /Users/asuarez/src/classnames
> node ./benchmarks/run
* local#strings x 7,708,933 ops/sec ±0.77% (96 runs sampled)
*   npm#strings x 7,653,876 ops/sec ±0.70% (96 runs sampled)
* local/dedupe#strings x 1,367,787 ops/sec ±0.70% (97 runs sampled)
*   npm/dedupe#strings x 1,202,487 ops/sec ±0.56% (96 runs sampled)
> Fastest is local#strings |   npm#strings
* local#object x 2,919,114 ops/sec ±0.78% (98 runs sampled)
*   npm#object x 2,904,197 ops/sec ±0.72% (100 runs sampled)
* local/dedupe#object x 2,386,335 ops/sec ±0.92% (93 runs sampled)
*   npm/dedupe#object x 1,893,136 ops/sec …
```

improve dedupe perf

---

.travis.yml
package.json

Instead of doing `npm run unit`, just configure it in a way that we can run `npm test`. This simplifies both `package.json` and `.travis.yml`

test configs: use standard testing pattern

---

index.js
tests/index.js

Arrays that are a 2nd parameter to  classNames, and arrays that contain empty nested arrays get pushed resulting in spaces at the end of the classNames function output. This PR fixes that issue.

Fix issue with empty arrays being pushed

---

.npmignore

Another option would be to add a `files` array to package.json.

Exclude bower.json and docs from npm package

---

tests/index.js

Nothing terribly important, but I added the test to test some assumptions after discovering that in the TypeScript definition "ClassDictionary" only allowed boolean values for property values passed into classNames.

explicitly test assumptions about all types of truthy and falsy property values

---

index.js

Fixes #99 
See https://github.com/JedWatson/classnames/issues/99#issuecomment-266185918

ES Module Export

---

bind.d.ts
index.d.ts
package.json

Add TypeScript declaration.

---

index.d.ts

Just exporting the additional types that the classnames function takes as arguments. Especially useful when you want to create a reusable component that accepts a `ClassValue` as a prop.

exported concealed types in TypeScript declaration file

---

benchmarks/package-lock.json
benchmarks/package.json
benchmarks/runSuite.js
package-lock.json
package.json

It turns out that some of dependencies contain vulnerabilities (even a critical one):
Changes:
- Upgrade dependencies to latest versions.
- Add lock files.
- Use `map` instead of `pluck` in benchmark project. [`pluck` was removed](https://github.com/lodash/lodash/wiki/Changelog#jan-12-2016--diff--docs) in later versions of Lodash.

Upgrade outdated dependencies

---

bind.js
dedupe.js
index.d.ts
index.js
package-lock.json
package.json
tests/bind.js

Firstly, this PR changes the first branch when unpacking object's, back to the primary behavior, with the `toString` behaviour as an addendum,  and fixes some of the mixed indentation that was merged previously.
Secondly, after updating the developer dependencies, I removed the `open-cli` test target and dependency,  as it attempts to `open` in a compatible program, but squashes any errors.
I don't think opening the default browser is useful when testing compared to maybe providing instructions in the README.

Minor cleanup

---

bind.d.ts
index.d.ts

These exports don’t exist in the implementation.

Remove named exports from type definitions

---

index.d.ts

A mapping consistes of classnames mapped to a value checked its booliness to
determine if the classnames should be added. These values may be anything,
they’re not related to the allowed class values.

Fix value types

---

index.js

Updated to use `hasOwnProperty` over trying to compare the Object prototype which fails with some build pipelines after transpilation. See issue #240.

Bugfix - Class names being returned as [object Object]

---

CONTRIBUTING.md
benchmarks/package.json

Also updates the contribution guidelines with the changes in running the benchmarks and adds a section to inform contributors to run tests in real browsers.

Add correct path to browser benchmarks

---

index.d.ts

When hovering over the function while using TypeScript, I want to see a quick description of what the function does.

Add description to the function TS definition

---

bind.d.ts
dedupe.d.ts
index.d.ts
tests/types.ts
tsconfig.json

The package uses commonjs, but it’s typed as if it contains faux ESM. This was problematic for people using `require` or the new `node16` module resolution.

Fix TypeScript types

---

benchmarks/package-lock.json
bind.js
dedupe.js
index.js
package-lock.json
tests/index.js

Builds on https://github.com/JedWatson/classnames/pull/255, thanks to @markdalgleish for the base code.
This pull request shortcuts the `toString.toString()` workaround by ensuring it fails the existing `arg.toString !== Object.prototype.toString` first.
Seeing as `toString` is an edge case in the first place, this balances our performance by having low to no impact in typical usage.
We have the option to shortcut with `hasOwnProperty('toString')` if that code path is desired. 
Benchmark results for this pull request
```
Mozilla/5.0 (X11; Linux x86_64; rv:104.0) Gecko/20100101 Firefox/104.0
* local#strings x 9,997,500 ops/sec ±1.21% (64 runs sampled)
* npm#strings x 10,106,445 ops/sec ±0.79% (66 runs sampled)
* local/dedupe#strings x 2,056,185 ops/sec ±0.34% (67 runs sampled)
* …
```

Fix toString as '[Object object]' in a vm

---

.github/workflows/release.yml

Reference https://docs.github.com/en/actions/publishing-packages/publishing-nodejs-packages

Add missing registry url for automated npm publish

---

README.md

Suggestion: Updates examples to functional components

Update README examples to use functional components

---

bind.d.ts
dedupe.d.ts
index.d.ts
tests/types.ts

It’s possible to support both a CJS export and a `.default` property by defining the export as an interface that has a call expression and a default property. This makes it possible to use `import classNames from 'classnames'` or `classNames.default('')`.
Also this packages exposes a UMD module, meaning `classNames` is available as a global when using a TypeScript script, but not when using a TypeScript module. This is supported by adding `export as namespace classNames`.
Technically this also declares it’s valid to use `classNames.default` when using `classNames` as a global. It may be better to move the line `classNames.default = classNames` outside of the if-statement at runtime.

Support default export and UMD

---

index.d.ts
tests/types.ts

Simple reproduction:
```typescript
const array = ['a', 'b', 'c'] as const;
classNames(array);
```
Error:
```
TS2345: Argument of type '[readonly ["a", "b", "c"]]' is not assignable to parameter of type 'ArgumentArray'.   Type 'readonly ["a", "b", "c"]' is not assignable to type 'Argument'.     Type 'readonly ["a", "b", "c"]' is not assignable to type 'Mapping'.       Index signature for type 'string' is missing in type 'readonly ["a", "b", "c"]'.
```
This PR adds a `ReadonlyArray<Argument>` to the `Argument` union type allowing `ReadonlyArray`s to be used with `classNames`

(Typescript) Allow `ReadonlyArray`s as valid classNames parameters

---

package-lock.json
package.json
tests/bind.js
tests/dedupe.js
tests/index.js

Replaces Mocha with Node.js' [built-in test runner](https://nodejs.org/api/test.html), reducing the amount of dependencies that need to be installed.

Replace Mocha with Node.js' built-in test runner

---

.npmignore

This file no longer exists, so there is no need to ignore it.

Remove `bower.json` from `.npmignore`

---

benchmarks/fixtures.js
benchmarks/index.html
benchmarks/package.json
benchmarks/run.js
benchmarks/runChecks.js
benchmarks/runInBrowser.js
benchmarks/runSuite.js

Changes the benchmark code so that modern JavaScript syntax is used where possible, including modules.

Use modern JavaScript syntax for benchmarks

---

.github/workflows/node.js.yml

Runs the benchmarks on CI. This is used as a simple smoke test to ensure the benchmarks do not break, and to prevent big regressions from getting introduced by accident.

Run benchmarks on CI

---

benchmarks/benchmarks.js
benchmarks/package.json
bind.js
index.js
package-lock.json

Replaces the logic that holds class names in an array and joins them together in the end with direct string concatenation, this results in ~30% performance increase across the board. The following benchmarks were ran on my 2021 MacBook Pro 14-inch with an M1 Pro chip running macOS Sonoma (14.2.1):
Benchmarking 'strings'.
| Task Name     | ops/sec    | Average Time (ns)  | Margin | Samples |
| ------------- | ---------- | ------------------ | ------ | ------- |
| default/local | 15,670,038 | 63.81605063010916  | ±0.54% | 7835020 |
| default/npm   | 9,005,011  | 111.04927211649938 | ±0.68% | 4502506 |
| bind/local    | 14,077,263 | 71.0365342300473   | ±0.18% | 7038632 |
| bind/npm      | 8,883,553  | 112.56756055795418 | ±1.65% | 4441778 |
| dedupe/local  | 4,010,081  | 249.37146821418366 …

Use string concatenation to increase performance

---

index.d.ts
tests/bind.test-d.ts
tests/dedupe.test-d.ts
tests/index.test-d.ts

Closes #294, as per https://github.com/JedWatson/classnames/issues/294#issuecomment-1870466528

Restore ability to pass TypeScript `interface`

---

package.json

Adds the [`exports` field](https://nodejs.org/api/packages.html#exports) to the package, which will explicitly define the exported surface of the library. Closes #321.

Add `exports` field to package

---

package.json

Fixes some warnings emitted by `npm publish`:
```
npm WARN publish npm auto-corrected some errors in your package.json when publishing.  Please run "npm pkg fix" to address these errors.
npm WARN publish errors corrected:
npm WARN publish "repository.url" was normalized to "git+https://github.com/JedWatson/classnames.git"
```

Fix URL for GIT repository in package

---

dedupe.js

Cleans up the code for the 'dedupe' variant to better match the code-style of the other entrypoints. This removes the immediately invoked function expression that was used to prevent variables from leaking into the global scope, as this is no longer possible now that this code is contained in a module.
This also sorts some methods and renames some variables, but otherwise doesn't touch the code, leading to similar performance to what we had before.

Clean up dedupe to better match other entrypoints

---

dedupe.js

Removes the code that clones the `arguments` for the dedupe variant, instead opting to pass it directly to the function that parses it as an array, reducing the amount of code required.
This seems to net slightly improved or similar performance under Node.js, Chrome and Safari, with only a small performance loss in Firefox (mostly within margin of error). The following benchmarks were ran on my 2021 MacBook Pro 14-inch with an M1 Pro chip running macOS Sonoma (14.2.1):
<details>
<summary>Node.js (v21.5.0)</summary>
Benchmarking 'strings'.
| Task Name    | ops/sec   | Average Time (ns)  | Margin | Samples |
| ------------ | --------- | ------------------ | ------ | ------- |
| dedupe/local | 4,162,768 | 240.22472536300643 | ±0.62% | 2081385 |
| dedupe/main  | 3,995,954 | 250.25309688105878 …

Do not clone `arguments` in dedupe

---

dedupe.js

Changes the dedupe variant so that the resulting class is built up using string concatenation, rather than joining an array. This is similar to the performance enhancements implemented under #336.
This yields significant performance improvements, or in the worst case equivalent performance. The following benchmarks were ran on my 2021 MacBook Pro 14-inch with an M1 Pro chip running macOS Sonoma (14.2.1):
<details>
<summary>Node.js (v21.5.0)</summary>
Benchmarking 'strings'.
| Task Name    | ops/sec   | Average Time (ns)  | Margin | Samples |
| ------------ | --------- | ------------------ | ------ | ------- |
| dedupe/local | 4,977,383 | 200.90875648794707 | ±0.55% | 2488692 |
| dedupe/main  | 4,092,089 | 244.37392188339444 | ±0.53% | 2046045 |
Benchmarking 'object'.
| Task Name    | …

Use string concatenation to speed up dedupe

---

README.md

The space in the code block has been replaced by a tab from two spaces in the PR [here](https://github.com/JedWatson/classnames/pull/303).
When I look at the space with tabs in preview, I feel the space is too wide, so I will change it back to two spaces.
- Current preview
- Preview after changes
Since the `const` declaration has been available from ES2015, I have used it to maintain consistency with other implementation examples.

Update README code space and variable declarations
